apiVersion: apps/v1
kind: Deployment
metadata:
   name: spring-boot-hello-kubernetes-deployment
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         bb: web
   template:
      metadata:
         labels:
            bb: web
      spec:
         containers:
            - name: spring-boot-hello-kubernetes
              image: com.acme/spring-boot-hello-kubernetes
              imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
   name: spring-boot-hello-kubernetes-service
   namespace: default
spec:
   type: NodePort
   selector:
      bb: web
   ports:
      - port: 8080
        targetPort: 8080
        nodePort: 30000
